name: build-push-docker.yml

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      image-name:
        type: string
        required: true
      context:
        type: string
        default: .
      docker-path-file:
        type: string
        required: false
        default: ''

jobs:
  build-and-push:
    name: ${{ inputs.name }} build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/actions/build-push-docker.yml
        with:
          name: ${{ inputs.name }}
          image-name: ${{ inputs.image-name }}
          context: ${{ inputs.context }}
          docker-path-file: ${{ inputs.docker-path-file }}