[versions]
kotlin = "2.3.21"
quarkus = "3.35.3"
junit = "5.10.0"
restassured = "5.4.0"
coroutines = "1.10.2"
kotlinLogging = "8.0.02"
slf4j = "2.0.17"
bcrypt = "0.10.2"
rest-assured = "5.5.1"
minidns = "1.1.1"
flyway = "12.6.1"
jackson = "2.18.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }

## core
quarkus-kotlin = { module = "io.quarkus:quarkus-kotlin", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
quarkus-bom = { module = "io.quarkus:quarkus-bom", version.ref = "quarkus" }
quarkus-credentials = { module = "io.quarkus:quarkus-credentials", version.ref = "quarkus" }

## rest
quarkus-resteasy-reactive = { module = "io.quarkus:quarkus-resteasy-reactive", version.ref = "quarkus" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkus" }

## databases
quarkus-hibernate-orm-panache-kotlin = { module = "io.quarkus:quarkus-hibernate-orm-panache-kotlin", version.ref = "quarkus" }
quarkus-jdbc-postgresql = { module = "io.quarkus:quarkus-jdbc-postgresql", version.ref = "quarkus" }
quarkus-hibernate-validator = { module = "io.quarkus:quarkus-hibernate-validator", version.ref = "quarkus" }
quarkus-flyway = { module = "io.quarkus:quarkus-flyway", version.ref = "quarkus" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

## auth
quarkus-smallrye-jwt = { module = "io.quarkus:quarkus-smallrye-jwt", version.ref = "quarkus" }
quarkus-smallrye-jwt-build = { module = "io.quarkus:quarkus-smallrye-jwt-build", version.ref = "quarkus" }

## other
quarkus-scheduler = { module = "io.quarkus:quarkus-scheduler", version.ref = "quarkus" }
quarkus-mailer = { module = "io.quarkus:quarkus-mailer", version.ref = "quarkus" }
quarkus-smallrye-health = { module = "io.quarkus:quarkus-smallrye-health", version.ref = "quarkus" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
minidns = { module = "org.minidns:minidns-hla", version.ref = "minidns" }
quarkus-redis = { module = "io.quarkus:quarkus-redis-client", version.ref = "quarkus" }
quarkus-rabbitmq = { module = "io.quarkus:quarkus-messaging-rabbitmq", version.ref = "quarkus" }

## test
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "restassured" }
quarkus-test-security = { module = "io.quarkus:quarkus-test-security", version.ref = "quarkus" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5", version.ref = "quarkus" }


