name: build-push-docker-native.yml
description: Build a Quarkus native executable and its Docker image

inputs:
  name:
    description: "backend module name"
    required: true
  docker-image:
    description: "Docker image name"
    required: true
  project-path-build:
    description: "Gradle project path"
    required: true
  dockerfile-path:
    description: "path to the native Dockerfile"
    required: true
  registry-token:
    required: false
    default: ''
    description: "registry token"
  context:
    required: true
    description: 'context application'
  push:
    required: false
    default: 'true'
    description: "push the image to the registry"

runs:
  using: 'composite'

  steps:
    - name: Install GraalVM
      uses: ./.github/actions/install-gradle
      with:
        java-version: '21'

    - name: Build native executable
      shell: bash
      run: ./gradlew ${{ inputs.project-path-build }}:assemble -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false -Dquarkus.native.container-build=false --no-daemon

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-${{ inputs.name }}-native
        path: ./backend/${{ inputs.name }}/build/*-runner
        retention-days: 7

    - name: Build Docker Image Native
      uses: ./.github/actions/build-push-docker
      with:
        name: ${{ inputs.name }}
        image-name: ${{ inputs.docker-image }}
        context: ${{ inputs.context }}
        docker-path-file: ${{ inputs.dockerfile-path }}
        registry-token: ${{ inputs.registry-token }}
        push: ${{ inputs.push }}
