name: build-push-docker-native.yml

inputs:
  name:
    type: string
    required: true
  docker-image:
    type: string
    required: true
  project-path-build:
    type: string
    required: true
  dockerfile-path:
    type: string
    required: true

runs:
  using: 'composite'

  steps:
    - name: Install GraalVM
      uses: ./.github/actions/install-gradle
      with:
        java-version: '21'

    - name: Build native executable
      shell: bash
      run: ./gradlew ${{ inputs.project-path-build }}:assemble -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false -Dquarkus.native.container-build=false --no-daemon

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-native
        path: ./build/${{ inputs.name }}/*-runner

    - name: Build Docker Image Native
      uses: ./.github/actions/build-push-docker
      with:
        name: ${{ inputs.name }}
        image-name: ${{ env.IMAGE_NAME }}
        context: .
        docker-path-file: ${{ inputs.dockerfile-path }}