## General
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.log.category."org.hibernate.validator".level=DEBUG
quarkus.log.category."io.smallrye.reactive.messaging".level=DEBUG
quarkus.http.port=8081

## single or cluster
scheduler.strategy=database
scheduler.worker.name=worker-primary

## Database
quarkus.datasource.username=uptime-kotlin
quarkus.datasource.password=uptime-kotlin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/uptime-kotlin
quarkus.hibernate-orm.mapping.format.global=ignore