## General
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.log.category."org.hibernate.validator".level=DEBUG
quarkus.http.port=8081

## single or cluster
scheduler.strategy=rabbitmq

## Database
quarkus.datasource.username=uptime-kotlin
quarkus.datasource.password=uptime-kotlin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/uptime-kotlin
quarkus.hibernate-orm.mapping.format.global=ignore

## Notifications jobs
mp.messaging.outgoing.notification-jobs-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.notification-jobs-out.queue.name=notification.jobs
mp.messaging.outgoing.notification-jobs-out.exchange.name=notification.jobs

mp.messaging.incoming.notification-jobs-in.connector=smallrye-rabbitmq
mp.messaging.incoming.notification-jobs-in.queue.name=notification.jobs
mp.messaging.incoming.notification-jobs-in.prefetch=1

## redis connexion
quarkus.redis.hosts=redis://:uptime-redis@localhost:6379

## RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=uptime-rabbitmq
rabbitmq-password=uptime-rabbitmq