## General
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.log.category."org.hibernate.validator".level=DEBUG

## Notifications jobs
mp.messaging.outgoing.notification-jobs-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.notification-jobs-out.queue.name=notification.jobs
mp.messaging.outgoing.notification-jobs-out.exchange.name=notification.jobs

mp.messaging.incoming.notification-jobs-in.connector=smallrye-rabbitmq
mp.messaging.incoming.notification-jobs-in.queue.name=notification.jobs
mp.messaging.incoming.notification-jobs-in.prefetch=1

## RabbitMQ
rabbitmq-host=rabbitmq
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest