name: front_security.yml

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '24'
      cache-path:
        type: string
        required: true
      working-directory:
        type: string
        required: true
      artifact-path:
        type: string
        required: true

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-path }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ inputs.artifact-path }}
          retention-days: 7