name: front_lint.yml

inputs:
  node-version:
    type: string
    default: '24'
  cache-path:
    type: string
    required: true
  working-directory:
    type: string
    required: true

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-path }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Run Prettier
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run format:check