## General
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.log.category."org.hibernate.validator".level=DEBUG
quarkus.http.port=8082

## single or cluster
scheduler.strategy=rabbitmq

## Database
quarkus.datasource.username=uptime-kotlin
quarkus.datasource.password=uptime-kotlin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/uptime-kotlin
quarkus.hibernate-orm.mapping.format.global=ignore

## Probe jobs
mp.messaging.outgoing.probe-jobs-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.probe-jobs-out.queue.name=probe.jobs
mp.messaging.outgoing.probe-jobs-out.exchange.name=probe.jobs

mp.messaging.incoming.probe-jobs-in.connector=smallrye-rabbitmq
mp.messaging.incoming.probe-jobs-in.queue.name=probe.jobs
mp.messaging.incoming.probe-jobs-in.exchange.name=probe.jobs

## Notifications jobs
mp.messaging.outgoing.notification-jobs-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.notification-jobs-out.queue.name=notification.jobs
mp.messaging.outgoing.notification-jobs-out.exchange.name=notification.jobs

## connexion redis
quarkus.redis.hosts=redis://:uptime-redis@localhost:6379

## RabbitMQ
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=uptime-rabbitmq
rabbitmq-password=uptime-rabbitmq

## Compilation native
quarkus.native.additional-build-args=\
--initialize-at-run-time=java.net.InetAddress,\
--initialize-at-run-time=java.net.Inet4Address,\
--initialize-at-run-time=java.net.Inet6Address,\
--initialize-at-run-time=org.minidns
quarkus.native.enable-http-url-handler=true
quarkus.native.enable-https-url-handler=true