## General
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.log.category."org.hibernate.validator".level=DEBUG

## Probe jobs
mp.messaging.outgoing.probe-jobs-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.probe-jobs-out.queue.name=probe.jobs
mp.messaging.outgoing.probe-jobs-out.exchange.name=probe.jobs

mp.messaging.incoming.probe-jobs-in.connector=smallrye-rabbitmq
mp.messaging.incoming.probe-jobs-in.queue.name=probe.jobs
mp.messaging.incoming.probe-jobs-in.prefetch=1  # ← 1 job à la fois par worker

## connexion redis
quarkus.redis.host=redis://localhost:6359

## RabbitMQ
rabbitmq-host=rabbitmq
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest