name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ 'apps/app/**', '.github/workflows/app-ci.yml' ]

env:
  WORKING_DIRECTORY: apps/app
  CACHE_PATH: apps/app/package-lock.json

jobs:
  vulnerability-scan:
    uses: ./.github/workflows/templates/front/front_security.yml
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}
      cache-path: ${{ env.CACHE_PATH }}

  lint:
    uses: ./.github/workflows/templates/front/front_lint.yml
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}
      cache-path: ${{ env.CACHE_PATH }}

  build:
    uses: ./.github/workflows/templates/front/front_build.yml
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}
      cache-path: ${{ env.CACHE_PATH }}
      artifact-path: apps/app/dist