name: App CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    paths: [ 'apps/app/**', '.github/workflows/app-ci.yml' ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/frontend/front-security
        with:
          working-directory: apps/app
          cache-path: apps/app/package-lock.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/frontend/front-lint
        with:
          working-directory: apps/app
          cache-path: apps/app/package-lock.json

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/frontend/front-build
        with:
          working-directory: apps/app
          cache-path: apps/app/package-lock.json
          artifact-path: apps/app/dist

