name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ 'apps/app/**', '.github/workflows/app-ci.yml' ]

jobs:
  vulnerability-scan:
    uses: ./.github/workflows/actions/frontend/front_security.yml
    with:
      working-directory: apps/app
      cache-path: apps/app/package-lock.json

  lint:
    uses: ./.github/workflows/actions/frontend/front_lint.yml
    with:
      working-directory: apps/app
      cache-path: apps/app/package-lock.json

  build:
    uses: ./.github/workflows/actions/frontend/front_build.yml
    with:
      working-directory: apps/app
      cache-path: apps/app/package-lock.json
      artifact-path: apps/app/dist