name: api-docker-build-and-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  api-build-native:
    name: api native build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: API native build
        uses: ./.github/actions/backend/build-push-docker-native
        with:
          name: api
          docker-image: api
          dockerfile-path: ./backend/api/src/main/docker/Dockerfile.native
          project-path-build: :backend:api
          registry-token: ${{ secrets.GH_TOKEN }}
          context: ./backend/api

  api-build-jvm:
    name: api jvm build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: API jvm build
        uses: ./.github/actions/backend/build-push-docker-jvm
        with:
          name: api
          docker-image: api-jvm
          dockerfile-path: ./backend/api/src/main/docker/Dockerfile.jvm
          project-path-build: :backend:api
          registry-token: ${{ secrets.GH_TOKEN }}
          context: ./backend/api

  worker-monitor-build-native:
    name: worker monitor native build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Worker monitor native build
        uses: ./.github/actions/backend/build-push-docker-native
        with:
          name: worker
          docker-image: worker
          dockerfile-path: ./backend/worker/src/main/docker/Dockerfile.native
          project-path-build: :backend:worker
          registry-token: ${{ secrets.GH_TOKEN }}
          context: ./backend/worker

  worker-monitor-build-jvm:
    name: worker monitor jvm build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Worker monitor jvm build
        uses: ./.github/actions/backend/build-push-docker-jvm
        with:
          name: worker
          docker-image: worker-jvm
          dockerfile-path: ./backend/worker/src/main/docker/Dockerfile.jvm
          project-path-build: :backend:worker
          registry-token: ${{ secrets.GH_TOKEN }}
          context: ./backend/worker

