name: api-docker-build-and-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  api-build-native:
    name: api native build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: API native build
        uses: ./.github/actions/backend/build-push-docker-native
        with:
          name: api
          docker-image: ghcr.io/${{ github.repository }}/api
          dockerfile-path: ./backend/api/src/main/docker/Dockerfile.native
          project-path-build: :backend:api
          registry-token: ${{ secrets.GH_TOKEN }}

  api-build-jvm:
    name: api jvm build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: API jvm build
        uses: ./.github/actions/backend/build-push-docker-jvm
        with:
          name: api
          docker-image: ghcr.io/${{ github.repository }}/api-jvm
          dockerfile-path: ./backend/api/src/main/docker/Dockerfile.jvm
          project-path-build: :backend:api
          registry-token: ${{ secrets.GH_TOKEN }}

  worker-monitor-build-native:
    name: worker monitor native build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Worker monitor native build
        uses: ./.github/actions/backend/build-push-docker-native
        with:
          name: worker-monitor
          docker-image: ghcr.io/${{ github.repository }}/worker-monitor
          dockerfile-path: ./backend/worker-monitor/src/main/docker/Dockerfile.native
          project-path-build: :backend:worker-monitor
          registry-token: ${{ secrets.GH_TOKEN }}

  worker-monitor-build-jvm:
    name: worker monitor jvm build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Worker monitor jvm build
        uses: ./.github/actions/backend/build-push-docker-jvm
        with:
          name: worker-monitor
          docker-image: ghcr.io/${{ github.repository }}/worker-monitor-jvm
          dockerfile-path: ./backend/worker-monitor/src/main/docker/Dockerfile.jvm
          project-path-build: :backend:worker-monitor
          registry-token: ${{ secrets.GH_TOKEN }}

  worker-notification-build-native:
    name: worker notification native build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Worker notification native build
        uses: ./.github/actions/backend/build-push-docker-native
        with:
          name: worker-notification
          docker-image: ghcr.io/${{ github.repository }}/worker-notification
          dockerfile-path: ./backend/worker-notification/src/main/docker/Dockerfile.native
          project-path-build: :backend:worker-notification
          registry-token: ${{ secrets.GH_TOKEN }}

  worker-notification-build-jvm:
    name: worker monitor jvm build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Worker notification jvm build
        uses: ./.github/actions/backend/build-push-docker-jvm
        with:
          name: worker-notification
          docker-image: ghcr.io/${{ github.repository }}/worker-notification-jvm
          dockerfile-path: ./backend/worker-notification/src/main/docker/Dockerfile.jvm
          project-path-build: :backend:worker-notification
          registry-token: ${{ secrets.GH_TOKEN }}