name: Website Docker Build & Push

on:
  push:
    tags: [ 'website-v*.*.*' ]
    paths: [ 'apps/website/**' ]

env:
  REGISTRY: ghcr.io

jobs:
  docker-website:
    name: Website Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build and push
        uses: ./.github/workflows/actions/build-push-docker.yml
        with:
          context: ./apps/website
          image-name: ${{ env.REGISTRY }}/${{ github.repository }}/website
          name: website
